/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:71c8d466-1965-41f9-a067-ccee0dec9868",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_nE1IPmAep",
    "aws_user_pools_web_client_id": "ee2dcfbdenpntj07l3pmnoau8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nywre4gykbh2tagedfsggprxvy.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fg5kle3lx5c67eusnflaoutrcm",
    "aws_user_files_s3_bucket": "mystorage20408-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
